<?php

namespace ContainerG7jubxg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GypMP10Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gypMP10' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gypMP10'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'propertyRepository' => ['privates', 'App\\Repository\\PropertyRepository', 'getPropertyRepositoryService', true],
        ], [
            'propertyRepository' => 'App\\Repository\\PropertyRepository',
        ]);
    }
}
