<?php

namespace ContainerG7jubxg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BopDyfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._bopDyf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._bopDyf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'image' => ['privates', '.errored..service_locator._bopDyf.App\\Entity\\Image', NULL, 'Cannot autowire service ".service_locator._bopDyf": it needs an instance of "App\\Entity\\Image" but this type has been excluded in "config/services.yaml".'],
        ], [
            'image' => 'App\\Entity\\Image',
        ]);
    }
}
