<?php

namespace ContainerG7jubxg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y5rugcsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y5rugcs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y5rugcs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'property' => ['privates', '.errored..service_locator.Y5rugcs.App\\Entity\\Property', NULL, 'Cannot autowire service ".service_locator.Y5rugcs": it needs an instance of "App\\Entity\\Property" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'property' => 'App\\Entity\\Property',
        ]);
    }
}
