<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Event__CLASSMETADATA__' => 0,
'App__Entity__Image__CLASSMETADATA__' => 1,
'App__Entity__Property__CLASSMETADATA__' => 2,
'App__Entity__Review__CLASSMETADATA__' => 3,
'App__Entity__Service__CLASSMETADATA__' => 4,
'App__Entity__Staff__CLASSMETADATA__' => 5,
'App__Entity__Payment__CLASSMETADATA__' => 6,
'App__Entity__Reservation__CLASSMETADATA__' => 7,
'App__Entity__User__CLASSMETADATA__' => 8,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Event',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\EventRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'description' => $o[3],
                    'date' => $o[4],
                    'location' => $o[5],
                    'price' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'date' => 'date',
                    'location' => 'location',
                    'price' => 'price',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'description' => 'description',
                    'date' => 'date',
                    'location' => 'location',
                    'price' => 'price',
                ],
            ],
            'table' => [
                [
                    'name' => 'event',
                ],
            ],
            'associationMappings' => [
                [
                    'images' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Event',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'text',
                'datetime',
                'string',
                'float',
            ],
            'fieldName' => [
                1 => 'id',
                'name',
                'description',
                'date',
                'location',
                'price',
            ],
            'columnName' => [
                1 => 'id',
                'name',
                'description',
                'date',
                'location',
                'price',
            ],
            'length' => [
                2 => 255,
                5 => 255,
            ],
            'nullable' => [
                6 => true,
            ],
            'fetch' => [
                7 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Event',
            ],
            'mappedBy' => [
                7 => 'event',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'images',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\Image',
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Image',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ImageRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'filename' => $o[2],
                    'mimeType' => $o[3],
                    'size' => $o[4],
                    'uploadedAt' => $o[5],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'filename' => 'filename',
                    'mime_type' => 'mimeType',
                    'size' => 'size',
                    'uploaded_at' => 'uploadedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'filename' => 'filename',
                    'mimeType' => 'mime_type',
                    'size' => 'size',
                    'uploadedAt' => 'uploaded_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'image',
                ],
            ],
            'associationMappings' => [
                [
                    'property' => $o[6],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Image',
                7 => 'property_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'integer',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'filename',
                'mimeType',
                'size',
                'uploadedAt',
            ],
            'columnName' => [
                1 => 'id',
                'filename',
                'mime_type',
                'size',
                'uploaded_at',
            ],
            'length' => [
                2 => 255,
                100,
            ],
            'nullable' => [
                3 => true,
                true,
                7 => true,
            ],
            'fetch' => [
                6 => 2,
            ],
            'sourceEntity' => [
                6 => 'App\\Entity\\Image',
            ],
            'inversedBy' => [
                6 => 'images',
            ],
            'sourceToTargetKeyColumns' => [
                6 => [
                    'property_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                6 => [
                    'id' => 'property_id',
                ],
            ],
            'joinColumns' => [
                6 => [
                    $o[7],
                ],
            ],
            'joinColumnFieldNames' => [
                6 => [
                    'property_id' => 'property_id',
                ],
            ],
            'referencedColumnName' => [
                7 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                6 => 'property',
            ],
            'targetEntity' => [
                6 => 'App\\Entity\\Property',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Property',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PropertyRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'number' => $o[2],
                    'type' => $o[3],
                    'price' => $o[4],
                    'status' => $o[5],
                    'capacity' => $o[6],
                    'size' => $o[7],
                    'shortdescription' => $o[8],
                    'longdescription' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'number' => 'number',
                    'type' => 'type',
                    'price' => 'price',
                    'status' => 'status',
                    'capacity' => 'capacity',
                    'size' => 'size',
                    'shortdescription' => 'shortdescription',
                    'longdescription' => 'longdescription',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'number' => 'number',
                    'type' => 'type',
                    'price' => 'price',
                    'status' => 'status',
                    'capacity' => 'capacity',
                    'size' => 'size',
                    'shortdescription' => 'shortdescription',
                    'longdescription' => 'longdescription',
                ],
            ],
            'table' => [
                [
                    'name' => 'property',
                ],
            ],
            'associationMappings' => [
                [
                    'reservations' => $o[10],
                    'images' => $o[11],
                ],
            ],
            'idGenerator' => [
                $o[12],
            ],
            'name' => [
                'App\\Entity\\Property',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'float',
                'string',
                'integer',
                'float',
                'string',
                'text',
            ],
            'fieldName' => [
                1 => 'id',
                'number',
                'type',
                'price',
                'status',
                'capacity',
                'size',
                'shortdescription',
                'longdescription',
            ],
            'columnName' => [
                1 => 'id',
                'number',
                'type',
                'price',
                'status',
                'capacity',
                'size',
                'shortdescription',
                'longdescription',
            ],
            'length' => [
                2 => 255,
                20,
                5 => 255,
                8 => 255,
            ],
            'nullable' => [
                7 => true,
                true,
                true,
            ],
            'fetch' => [
                10 => 2,
                2,
            ],
            'sourceEntity' => [
                10 => 'App\\Entity\\Property',
                'App\\Entity\\Property',
            ],
            'mappedBy' => [
                10 => 'property',
                'property',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                10 => 'reservations',
                'images',
            ],
            'targetEntity' => [
                10 => 'App\\Entity\\Reservation',
                'App\\Entity\\Image',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Review',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ReviewRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'note' => $o[2],
                    'commentaire' => $o[3],
                    'date_creation' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'note' => 'note',
                    'commentaire' => 'commentaire',
                    'date_creation' => 'date_creation',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'note' => 'note',
                    'commentaire' => 'commentaire',
                    'date_creation' => 'date_creation',
                ],
            ],
            'table' => [
                [
                    'name' => 'review',
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\Review',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'integer',
                'string',
                'datetime_immutable',
            ],
            'fieldName' => [
                1 => 'id',
                'note',
                'commentaire',
                'date_creation',
            ],
            'columnName' => [
                1 => 'id',
                'note',
                'commentaire',
                'date_creation',
            ],
            'length' => [
                3 => 255,
            ],
            'nullable' => [
                3 => true,
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Service',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ServiceRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'price' => $o[3],
                    'description' => $o[4],
                    'category' => $o[5],
                    'servtime' => $o[6],
                    'location' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'price' => 'price',
                    'description' => 'description',
                    'category' => 'category',
                    'servtime' => 'servtime',
                    'location' => 'location',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'price' => 'price',
                    'description' => 'description',
                    'category' => 'category',
                    'servtime' => 'servtime',
                    'location' => 'location',
                ],
            ],
            'table' => [
                [
                    'name' => 'service',
                ],
            ],
            'associationMappings' => [
                [
                    'reservations' => $o[8],
                    'images' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[10],
            ],
            'name' => [
                'App\\Entity\\Service',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'float',
                'text',
                'string',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'price',
                'description',
                'category',
                'servtime',
                'location',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'price',
                'description',
                'category',
                'servtime',
                'location',
            ],
            'length' => [
                2 => 255,
                5 => 100,
                255,
                255,
            ],
            'nullable' => [
                6 => true,
                true,
            ],
            'fetch' => [
                8 => 2,
                2,
            ],
            'sourceEntity' => [
                8 => 'App\\Entity\\Service',
                'App\\Entity\\Service',
            ],
            'mappedBy' => [
                8 => 'services',
                'service',
            ],
            'cascade' => [
                9 => [
                    'persist',
                    'remove',
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                8 => 'reservations',
                'images',
            ],
            'targetEntity' => [
                8 => 'App\\Entity\\Reservation',
                'App\\Entity\\Image',
            ],
        ],
    ],
    $o[0],
    []
); } },
5 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Staff',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\StaffRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'nom' => $o[2],
                    'poste' => $o[3],
                    'numtel' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'poste' => 'poste',
                    'numtel' => 'numtel',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'nom' => 'nom',
                    'poste' => 'poste',
                    'numtel' => 'numtel',
                ],
            ],
            'table' => [
                [
                    'name' => 'staff',
                ],
            ],
            'associationMappings' => [
                [
                    'reservations' => $o[5],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\Staff',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'nom',
                'poste',
                'numtel',
            ],
            'columnName' => [
                1 => 'id',
                'nom',
                'poste',
                'numtel',
            ],
            'length' => [
                2 => 255,
                255,
                255,
            ],
            'fetch' => [
                5 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Staff',
            ],
            'mappedBy' => [
                5 => 'staff',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'reservations',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\Reservation',
            ],
        ],
    ],
    $o[0],
    []
); } },
6 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Payment',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\PaymentRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'montant' => $o[2],
                    'methode' => $o[3],
                    'statut' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'montant' => 'montant',
                    'methode' => 'methode',
                    'statut' => 'statut',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'montant' => 'montant',
                    'methode' => 'methode',
                    'statut' => 'statut',
                ],
            ],
            'table' => [
                [
                    'name' => 'payment',
                ],
            ],
            'associationMappings' => [
                [
                    'reservation' => $o[5],
                ],
            ],
            'idGenerator' => [
                $o[7],
            ],
            'name' => [
                'App\\Entity\\Payment',
                6 => 'reservation_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'float',
                'string',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'montant',
                'methode',
                'statut',
            ],
            'columnName' => [
                1 => 'id',
                'montant',
                'methode',
                'statut',
            ],
            'length' => [
                3 => 255,
                255,
            ],
            'cascade' => [
                5 => [
                    'persist',
                    'remove',
                ],
            ],
            'fetch' => [
                5 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Payment',
            ],
            'sourceToTargetKeyColumns' => [
                5 => [
                    'reservation_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                5 => [
                    'id' => 'reservation_id',
                ],
            ],
            'joinColumns' => [
                5 => [
                    $o[6],
                ],
            ],
            'joinColumnFieldNames' => [
                5 => [
                    'reservation_id' => 'reservation_id',
                ],
            ],
            'deferrable' => [
                6 => false,
            ],
            'unique' => [
                6 => true,
            ],
            'nullable' => [
                6 => false,
            ],
            'referencedColumnName' => [
                6 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'reservation',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\Reservation',
            ],
        ],
    ],
    $o[0],
    []
); } },
7 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Reservation',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\ReservationRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'dateArrivee' => $o[2],
                    'dateDepart' => $o[3],
                    'statut' => $o[4],
                    'nombrePersonnes' => $o[5],
                    'totalPrice' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'date_arrivee' => 'dateArrivee',
                    'date_depart' => 'dateDepart',
                    'statut' => 'statut',
                    'nombre_personnes' => 'nombrePersonnes',
                    'total_price' => 'totalPrice',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'dateArrivee' => 'date_arrivee',
                    'dateDepart' => 'date_depart',
                    'statut' => 'statut',
                    'nombrePersonnes' => 'nombre_personnes',
                    'totalPrice' => 'total_price',
                ],
            ],
            'table' => [
                [
                    'name' => 'reservation',
                ],
            ],
            'associationMappings' => [
                [
                    'user' => $o[7],
                    'staff' => $o[9],
                    'services' => $o[11],
                ],
            ],
            'idGenerator' => [
                $o[15],
            ],
            'name' => [
                'App\\Entity\\Reservation',
                8 => 'user_id',
                10 => 'staff_id',
                12 => 'reservation_service',
                'reservation_id',
                'service_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
                'datetime',
                'string',
                'integer',
                'float',
            ],
            'fieldName' => [
                1 => 'id',
                'dateArrivee',
                'dateDepart',
                'statut',
                'nombrePersonnes',
                'totalPrice',
            ],
            'columnName' => [
                1 => 'id',
                'date_arrivee',
                'date_depart',
                'statut',
                'nombre_personnes',
                'total_price',
            ],
            'length' => [
                4 => 50,
            ],
            'fetch' => [
                7 => 2,
                9 => 2,
                11 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Reservation',
                9 => 'App\\Entity\\Reservation',
                11 => 'App\\Entity\\Reservation',
            ],
            'inversedBy' => [
                7 => 'reservations',
                9 => 'reservations',
                11 => 'reservations',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'user_id' => 'id',
                ],
                9 => [
                    'staff_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'user_id',
                ],
                9 => [
                    'id' => 'staff_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
                9 => [
                    $o[10],
                ],
                12 => [
                    $o[13],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'user_id' => 'user_id',
                ],
                9 => [
                    'staff_id' => 'staff_id',
                ],
            ],
            'deferrable' => [
                8 => false,
                10 => false,
            ],
            'unique' => [
                8 => false,
                10 => false,
            ],
            'nullable' => [
                8 => false,
                10 => true,
                13 => false,
                false,
            ],
            'referencedColumnName' => [
                8 => 'id',
                10 => 'id',
                13 => 'id',
                'id',
            ],
            'onDelete' => [
                10 => 'SET NULL',
                13 => 'CASCADE',
                'CASCADE',
            ],
            'isOnDeleteCascade' => [
                11 => true,
            ],
            'joinTable' => [
                11 => $o[12],
            ],
            'joinTableColumns' => [
                11 => [
                    'reservation_id',
                    'service_id',
                ],
            ],
            'relationToSourceKeyColumns' => [
                11 => [
                    'reservation_id' => 'id',
                ],
            ],
            'relationToTargetKeyColumns' => [
                11 => [
                    'service_id' => 'id',
                ],
            ],
            'inverseJoinColumns' => [
                12 => [
                    $o[14],
                ],
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'user',
                9 => 'staff',
                11 => 'services',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\User',
                9 => 'App\\Entity\\Staff',
                11 => 'App\\Entity\\Service',
            ],
        ],
    ],
    $o[0],
    []
); } },
8 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'email' => $o[2],
                    'roles' => $o[3],
                    'password' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                ],
            ],
            'table' => [
                [
                    'name' => 'user',
                    'quoted' => true,
                ],
            ],
            'associationMappings' => [
                [
                    'reservations' => $o[5],
                ],
            ],
            'idGenerator' => [
                $o[6],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'json',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
            ],
            'columnName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
            ],
            'length' => [
                2 => 180,
            ],
            'unique' => [
                2 => true,
            ],
            'fetch' => [
                5 => 2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\User',
            ],
            'mappedBy' => [
                5 => 'user',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'reservations',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\Reservation',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
