<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XmtwBk4Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xmtwBk4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xmtwBk4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'property' => ['privates', '.errored..service_locator.xmtwBk4.App\\Entity\\Property', NULL, 'Cannot autowire service ".service_locator.xmtwBk4": it needs an instance of "App\\Entity\\Property" but this type has been excluded in "config/services.yaml".'],
        ], [
            'property' => 'App\\Entity\\Property',
        ]);
    }
}
