<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H5GyOEOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.h5GyOEO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h5GyOEO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'staff' => ['privates', '.errored..service_locator.h5GyOEO.App\\Entity\\Staff', NULL, 'Cannot autowire service ".service_locator.h5GyOEO": it needs an instance of "App\\Entity\\Staff" but this type has been excluded in "config/services.yaml".'],
        ], [
            'staff' => 'App\\Entity\\Staff',
        ]);
    }
}
