<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDashboardControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AdminDashboardController' shared autowired service.
     *
     * @return \App\Controller\AdminDashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AdminDashboardController'] = $instance = new \App\Controller\AdminDashboardController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\AdminDashboardController', $container));

        return $instance;
    }
}
