<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProperty2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xmtwBk4.App\Entity\Property' shared service.
     *
     * @return \App\Entity\Property
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xmtwBk4": it needs an instance of "App\\Entity\\Property" but this type has been excluded in "config/services.yaml".');
    }
}
