<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PropertyController' shared autowired service.
     *
     * @return \App\Controller\PropertyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PropertyController'] = $instance = new \App\Controller\PropertyController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PropertyController', $container));

        return $instance;
    }
}
