<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PaymentRepository' shared autowired service.
     *
     * @return \App\Repository\PaymentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PaymentRepository'] = new \App\Repository\PaymentRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
