<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RoomType' shared autowired service.
     *
     * @return \App\Form\RoomType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RoomType'] = new \App\Form\RoomType();
    }
}
