<?php

namespace ContainerAUl61Gk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaffTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\StaffType' shared autowired service.
     *
     * @return \App\Form\StaffType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\StaffType'] = new \App\Form\StaffType();
    }
}
