<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAUl61Gk\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAUl61Gk/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAUl61Gk.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAUl61Gk\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAUl61Gk\App_KernelProdContainer([
    'container.build_hash' => 'AUl61Gk',
    'container.build_id' => '601b86e6',
    'container.build_time' => 1767964096,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAUl61Gk');
