<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateArrivee' => [parent::class, 'dateArrivee', null, 16],
        "\0".parent::class."\0".'dateDepart' => [parent::class, 'dateDepart', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nombrePersonnes' => [parent::class, 'nombrePersonnes', null, 16],
        "\0".parent::class."\0".'services' => [parent::class, 'services', null, 16],
        "\0".parent::class."\0".'staff' => [parent::class, 'staff', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'totalPrice' => [parent::class, 'totalPrice', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'dateArrivee' => [parent::class, 'dateArrivee', null, 16],
        'dateDepart' => [parent::class, 'dateDepart', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nombrePersonnes' => [parent::class, 'nombrePersonnes', null, 16],
        'services' => [parent::class, 'services', null, 16],
        'staff' => [parent::class, 'staff', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'totalPrice' => [parent::class, 'totalPrice', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
