<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Property extends \App\Entity\Property implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'capacity' => [parent::class, 'capacity', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null, 16],
        "\0".parent::class."\0".'longdescription' => [parent::class, 'longdescription', null, 16],
        "\0".parent::class."\0".'number' => [parent::class, 'number', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'shortdescription' => [parent::class, 'shortdescription', null, 16],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'capacity' => [parent::class, 'capacity', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'images' => [parent::class, 'images', null, 16],
        'longdescription' => [parent::class, 'longdescription', null, 16],
        'number' => [parent::class, 'number', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'shortdescription' => [parent::class, 'shortdescription', null, 16],
        'size' => [parent::class, 'size', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
