<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Image extends \App\Entity\Image implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'filename' => [parent::class, 'filename', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null, 16],
        "\0".parent::class."\0".'mimeType' => [parent::class, 'mimeType', null, 16],
        "\0".parent::class."\0".'property' => [parent::class, 'property', null, 16],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null, 16],
        "\0".parent::class."\0".'uploadedAt' => [parent::class, 'uploadedAt', null, 16],
        'filename' => [parent::class, 'filename', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageFile' => [parent::class, 'imageFile', null, 16],
        'mimeType' => [parent::class, 'mimeType', null, 16],
        'property' => [parent::class, 'property', null, 16],
        'size' => [parent::class, 'size', null, 16],
        'uploadedAt' => [parent::class, 'uploadedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
