<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payment extends \App\Entity\Payment implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'methode' => [parent::class, 'methode', null, 16],
        "\0".parent::class."\0".'montant' => [parent::class, 'montant', null, 16],
        "\0".parent::class."\0".'reservation' => [parent::class, 'reservation', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'methode' => [parent::class, 'methode', null, 16],
        'montant' => [parent::class, 'montant', null, 16],
        'reservation' => [parent::class, 'reservation', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
